version: '3.9'

services:
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5555:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
