version: '3.9'

services:
  database:
    image: postgres:14-alpine
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./database:/var/lib/postgresql/data